# Generated by Django 3.0.6 on 2020-06-01 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupID', models.IntegerField(primary_key=True, serialize=False)),
                ('groupName', models.TextField()),
                ('groupDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserA',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.TextField()),
                ('allowDigitalTime', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('linkID', models.IntegerField(primary_key=True, serialize=False)),
                ('groupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overview.Group')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overview.UserA')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityID', models.IntegerField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=500)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('activityImage', models.TextField()),
                ('isComplete', models.BooleanField()),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overview.UserA')),
            ],
        ),
    ]
