# Generated by Django 3.0.6 on 2020-06-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usera',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
