# Generated by Django 3.0.6 on 2020-06-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_auto_20200602_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='GroupID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='linkID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
